# Intelligence Layer Configuration Example
#
# This file shows the structure for intelligence layer configuration.
# Copy to intelligence.yaml and customize for your environment.

# Market state configuration
market_state_ttl_secs: 30  # How long to keep state before considering it stale

# Beta dataplane connection settings
dataplane:
  # Kafka configuration
  kafka_brokers: "localhost:9092"
  kafka_topics:
    - "qenus.beta.features.amm"
    - "qenus.beta.features.gas"
    - "qenus.beta.features.bridge"
    - "qenus.beta.features.flashloan"
    - "qenus.beta.features.sequencer"
  
  # gRPC configuration
  grpc_endpoint: "http://localhost:50053"
  
  # Connection mode: "kafka", "grpc", or "mock"
  mode: "mock"

# Detection settings
detection:
  interval_secs: 5  # Run detection every 5 seconds
  max_candidates_per_cycle: 100
  min_confidence: 0.7  # Minimum confidence to emit candidate

# Strategy configurations
# NOTE: These will eventually be loaded from business/ module
# For now, they're defined here as defaults
strategies:
  triangle_arb:
    name: "triangle_arb"
    enabled: true
    min_profit_usd: 500.0
    min_profit_bps: 10.0  # 0.1% minimum spread
    max_position_usd: 5000000.0
    approved_assets:
      - "WETH"
      - "USDC"
      - "USDT"
      - "WBTC"
    approved_chains:
      - Ethereum
      - Arbitrum
      - Optimism
      - Base
    risk_limits:
      max_slippage_bps: 100.0  # 1% max slippage
      max_gas_pct: 50.0  # Gas can be up to 50% of profit
      max_bridge_latency_secs: 300  # 5 minutes max
      min_success_prob: 0.8  # 80% minimum success probability
  
  dex_arb:
    name: "dex_arb"
    enabled: true
    min_profit_usd: 200.0
    min_profit_bps: 5.0  # 0.05% minimum spread
    max_position_usd: 2000000.0
    approved_assets:
      - "WETH"
      - "USDC"
      - "USDT"
      - "DAI"
      - "WBTC"
      - "stETH"
    approved_chains:
      - Ethereum
      - Arbitrum
      - Optimism
      - Base
    risk_limits:
      max_slippage_bps: 50.0  # 0.5% max slippage
      max_gas_pct: 30.0
      max_bridge_latency_secs: 0  # No bridge for same-chain
      min_success_prob: 0.85  # 85% minimum (higher for same-chain)

